name: Container Image Scan - Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Trivy scan on Docker image
        uses: aquasecurity/trivy-action@v0.3.0
        with:
          image-ref: 'your-docker-image:tag'  # Replace with your image name and tag
          
      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-scan-report
          path: trivy-report.json